services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb

#Implementing types of data bases
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=809117Aa*
    volumes:
      - mongo_data:/data/db

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_ui
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: Java#1501POAr$
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db

volumes:
  mongo_data:
    driver: local
  postgres_data:
