spring.config.import=optional:file:.env[.properties]
spring.datasource.driver-class.name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/library_db 

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb://admin:809117Aa*@localhost:27017/library_db?authSource=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=809117Aa*

