name: library_ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."
      - run: mvn build
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."
      - run: mvn test