name: library_ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn validate
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean test
  verify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Verifying..."
      - run: mvn verify