name: library_ci
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."
      - run: mvn validate
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Testing..."
#      - run: mvn clean test
#    verify:
#      runs-on: ubuntu-latest
#      steps:
#        - run: echo "Verifying..."
#        - run: mvn verify