name: library_ci
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: echo "Building..."
      - run: mvn validate
#    steps:
#      - run: echo "Testing..."
#      - run: mvn clean test
#    steps:
#     - run: echo "Verifying..."
#     - run: mvn verify